import { useState } from 'react';
import { FileText, Shield, Cookie, Copyright as CopyrightIcon, X, AlertTriangle } from 'lucide-react';

/**
 * Single source of truth for all legal copy shown in-app. Previously this
 * lived duplicated inside SignupPage.jsx; now SignupPage and
 * CookieConsentBanner both render the same modal against the same content,
 * so there's one place to update wording, add a section, or bump the
 * "last updated" date.
 */
export const LEGAL_CONTENT = {
  terms: {
    title: 'Terms of Service',
    icon: FileText,
    sections: [
      {
        heading: '1. Acceptance of Terms',
        body: 'By accessing or using ERJ Smart Solutions ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not access or use the Service.',
      },
      {
        heading: '2. Use of Service',
        body: 'You may use the Service only for lawful purposes and in accordance with these Terms. You agree not to use the Service in any way that violates applicable laws or regulations, or in any manner that could damage, disable, overburden, or impair the Service.',
      },
      {
        heading: '3. Account Registration',
        body: 'To access certain features, you must register for an account. You agree to provide accurate, current, and complete information during registration and to update such information as needed. You are responsible for maintaining the confidentiality of your account credentials, and for all activity that occurs under your account.',
      },
      {
        heading: '4. Subscription & Billing',
        body: 'Paid plans are billed monthly per enrolled employee. You authorize ERJ Smart Solutions to charge your payment method on file. All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days notice.',
      },
      {
        heading: '5. Data Ownership',
        body: 'You retain ownership of all data you upload or create in the Service. You grant us a limited license to process that data solely to provide the Service to you. We will not sell or share your data with third parties without your consent.',
      },
      {
        heading: '6. Termination',
        body: 'Either party may terminate this agreement at any time. Upon termination, your access to the Service will cease. We will retain your data for 30 days following termination, after which it will be permanently deleted.',
      },
      {
        heading: '7. Service Availability & Risk',
        body: 'The Service is provided on an "as available" basis. We target high uptime but do not guarantee the Service will be uninterrupted, error-free, or available at all times — outages, maintenance windows, third-party network issues, or events outside our control (force majeure) can affect access. Attendance, leave, overtime, and payroll-related figures generated by the Service are calculated from the data your organization enters; you are responsible for reviewing and verifying that data — including hours, leave balances, and exported reports — before relying on it for payroll, compliance, or other decisions. Loss of internet connectivity, browser data, or a device can result in unsaved in-progress entries (e.g. an unsubmitted attendance or leave form) being lost; the Service auto-saves drafts locally where possible, but this is a convenience, not a guarantee.',
      },
      {
        heading: '8. Security Disclaimer',
        body: 'We use industry-standard safeguards (see our Privacy Policy) to protect your data, but no method of electronic storage or transmission is 100% secure, and we cannot guarantee absolute security. You are responsible for keeping your own login credentials confidential and for enabling two-factor authentication where available. Notify us promptly at security@erj.ph if you suspect unauthorized access to your account.',
      },
      {
        heading: '9. Disclaimer of Warranties & Limitation of Liability',
        body: 'To the fullest extent permitted by law, the Service is provided without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, and non-infringement. ERJ Smart Solutions shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including lost profits, lost data, or payroll errors arising from unverified figures — arising out of or related to your use of the Service. Our total liability for any claim arising from these Terms is limited to the amount you paid us in the 12 months preceding the claim.',
      },
      {
        heading: '10. Governing Law',
        body: 'These Terms shall be governed by and construed in accordance with the laws of the Republic of the Philippines, without regard to its conflict of law provisions.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    icon: Shield,
    sections: [
      {
        heading: '1. Information We Collect',
        body: 'We collect information you provide directly, such as your name, email address, company details, and payment information. We also collect usage data, device information, approximate location (for security checks like new-country or new-IP sign-in alerts), and log data when you interact with the Service.',
      },
      {
        heading: '2. How We Use Your Information',
        body: 'We use your information to provide, maintain, and improve the Service; process transactions; send transactional and promotional communications; monitor and analyze usage patterns; detect fraud and account-security risks; and comply with legal obligations.',
      },
      {
        heading: '3. Data Storage & Security',
        body: 'Your data is stored on secure servers within your selected region. We implement industry-standard security measures including 256-bit SSL encryption, regular security audits, and access controls to protect your data from unauthorized access. As noted in our Terms, no system is completely secure, and we encourage strong, unique passwords and two-factor authentication.',
      },
      {
        heading: '4. Data Sharing',
        body: 'We do not sell your personal data. We may share data with trusted service providers (e.g. hosting, email delivery, payment processing) who assist in operating the Service, subject to confidentiality agreements. We may disclose data if required by law, by valid legal process, or to protect the rights, property, or safety of our users or the public.',
      },
      {
        heading: '5. Cookies & Similar Technologies',
        body: 'We use strictly necessary cookies/local storage to keep you signed in and enforce session-security rules (e.g. automatic sign-out after inactivity or at midnight). With your consent, we also use a small number of convenience cookies — for example, remembering the email you last signed in with so you don\u2019t have to retype it. See our Cookie Policy for the full list and how to withdraw consent at any time.',
      },
      {
        heading: '6. Your Rights',
        body: 'You have the right to access, correct, or delete your personal data at any time. You may also object to processing or request data portability. To exercise these rights, contact our Data Protection Officer at privacy@erj.ph.',
      },
      {
        heading: '7. Data Retention',
        body: 'We retain your data for as long as your account is active or as needed to provide the Service. After account termination, data is retained for 30 days before permanent deletion, unless longer retention is required by law.',
      },
      {
        heading: '8. Contact Us',
        body: 'For questions about this Privacy Policy or our data practices, please contact us at privacy@erj.ph or write to ERJ Smart Solutions, 8F BGC Corporate Center, 30th Street, Bonifacio Global City, Taguig City, Metro Manila, Philippines.',
      },
    ],
  },
  cookies: {
    title: 'Cookie Policy',
    icon: Cookie,
    sections: [
      {
        heading: '1. Strictly Necessary (always on)',
        body: 'These keep the Service working and cannot be turned off: staying signed in between page loads, enforcing session-security rules (automatic sign-out after 30 minutes of inactivity, or at midnight for standard sessions / 24 hours for "Remember me"), and remembering your cookie-consent choice itself. These never contain your password and are not used for advertising.',
      },
      {
        heading: '2. Convenience (only with your consent)',
        body: 'If you click "Accept" on the cookie banner, we set one small cookie that remembers the email address you last signed in with, so the sign-in form is pre-filled next time. If you click "Decline" (or later withdraw consent), this cookie is not set, and any existing one is deleted immediately.',
      },
      {
        heading: '3. What We Don\u2019t Do',
        body: 'We do not use third-party advertising or cross-site tracking cookies. We do not sell cookie or browsing data to anyone.',
      },
      {
        heading: '4. Managing Cookies',
        body: 'You can change your decision at any time from your account\u2019s Settings page, or by clearing cookies for this site in your browser. Blocking strictly-necessary cookies in your browser will prevent the Service from keeping you signed in.',
      },
    ],
  },
  copyright: {
    title: 'Copyright',
    icon: CopyrightIcon,
    sections: [
      {
        heading: '1. Ownership',
        body: '\u00a9 2026 ERJ Smart Solutions. All rights reserved. The Service \u2014 including its software, source code, design, layout, graphics, logos, and the "ERJ Smart Solutions" name and marks \u2014 is the property of ERJ Smart Solutions and is protected by Philippine and international copyright, trademark, and other intellectual property laws.',
      },
      {
        heading: '2. Your Data',
        body: 'This copyright notice covers the Service itself, not the data you enter into it. As stated in our Terms of Service, you retain ownership of all attendance, employee, and company data you create or upload \u2014 we do not claim any copyright over it.',
      },
      {
        heading: '3. Third-Party Material',
        body: 'The Service may incorporate open-source libraries and other third-party components, each governed by its own license. A full list of these components and their licenses is available on request at legal@erj.ph.',
      },
      {
        heading: '4. Restrictions',
        body: 'You may not copy, modify, distribute, sell, lease, reverse-engineer, or create derivative works based on the Service, in whole or in part, except as expressly permitted by these terms or by applicable law.',
      },
      {
        heading: '5. Reporting Infringement',
        body: 'If you believe material on the Service infringes your copyright, please contact us at legal@erj.ph with a description of the work, its location within the Service, and your contact details, and we will investigate promptly.',
      },
    ],
  },
};

const TABS = [
  { key: 'terms', label: 'Terms' },
  { key: 'privacy', label: 'Privacy' },
  { key: 'cookies', label: 'Cookies' },
  { key: 'copyright', label: 'Copyright' },
];

/**
 * `type` sets which document opens first; the person can switch tabs
 * without closing the modal. `onClose` is called on "Got it" / the X / a
 * backdrop click.
 */
export default function LegalModal({ type = 'terms', onClose }) {
  const [active, setActive] = useState(LEGAL_CONTENT[type] ? type : 'terms');
  const content = LEGAL_CONTENT[active];
  const Icon = content.icon;

  return (
    <div
      className="fixed inset-0 z-[9999] flex items-center justify-center p-4"
      style={{ background: 'rgba(15,23,42,0.6)', backdropFilter: 'blur(4px)' }}
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl w-full max-w-lg max-h-[85vh] flex flex-col overflow-hidden"
        style={{ boxShadow: '0 24px 64px rgba(0,0,0,0.18), 0 2px 8px rgba(0,0,0,0.08)' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 pt-5" style={{ borderBottom: '1px solid #e2e8f0' }}>
          <div className="flex items-center gap-3 pb-4">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{ background: 'rgba(99,102,241,0.1)' }}>
              <Icon size={16} style={{ color: '#6366f1' }} />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">{content.title}</h2>
              <p className="text-xs text-slate-400">ERJ Smart Solutions · Last updated July 2026</p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close"
            className="p-1.5 -mt-1 rounded-full text-slate-300 hover:text-slate-500 hover:bg-slate-50 transition-colors shrink-0"
          >
            <X size={18} />
          </button>
        </div>

        {/* Tab switcher */}
        <div className="flex items-center gap-1 px-6 pt-3" style={{ borderBottom: '1px solid #e2e8f0' }}>
          {TABS.map(t => (
            <button
              key={t.key}
              onClick={() => setActive(t.key)}
              className="px-3 py-2 text-xs font-semibold rounded-t-lg transition-colors"
              style={
                active === t.key
                  ? { color: '#4f46e5', borderBottom: '2px solid #6366f1', marginBottom: '-1px' }
                  : { color: '#94a3b8', borderBottom: '2px solid transparent', marginBottom: '-1px' }
              }
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* Scrollable body */}
        <div className="overflow-y-auto flex-1 px-6 py-5 space-y-5">
          {active === 'terms' && (
            <div className="flex items-start gap-2.5 p-3 rounded-xl text-xs text-amber-800" style={{ background: '#fffbeb', border: '1px solid #fde68a' }}>
              <AlertTriangle size={14} className="shrink-0 mt-0.5" />
              <span>Sections 7–9 cover service-availability risk, security limitations, and liability — please review these before relying on the Service for payroll or compliance decisions.</span>
            </div>
          )}
          {content.sections.map(s => (
            <div key={s.heading}>
              <h3 className="text-sm font-bold text-slate-800 mb-1.5">{s.heading}</h3>
              <p className="text-sm text-slate-500 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 flex justify-end" style={{ borderTop: '1px solid #e2e8f0', background: '#f8fafc' }}>
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl text-sm font-bold text-white"
            style={{ background: 'linear-gradient(135deg, #6366f1, #4f46e5)', boxShadow: '0 4px 14px rgba(99,102,241,0.3)' }}
          >
            Aggree & Close
          </button>
        </div>
      </div>
    </div>
  );
}
